language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t axbattai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true axbattai/docker-react npm run test

